### ISSUE TITLE
Why did you blacklist my pool?

### ISSUE THREAD

**Issue by nardholio** [balancer-labs/pool-management-vue#153]
What's wrong with Dentacoin?

https://pools.balancer.exchange/#/pool/0xd6dc678b03b3986630808c63a431f4104a7da8c2/

**Comment by nardholio** [comment]
Why is it bad ERC20 token?

**Comment by Destiner** [comment]
As per [Round 14](https://forum.balancer.finance/t/bal-whitelist-round-14/429) on forum:

> The following token breaks expected ERC-20 transfer() behavior in a few ways; most notably there is an optional token-for-gas mechanism which would cause all transfers out of a Balancer pool to signal failure, thereby locking funds. This unconventional behavior violates Whitelist Criterion 3: The token’s transfer() and transferFrom() implementations must exhibit the expected behavior - namely, transferring N tokens from one address to another. Certain divergences from this behavior, such as transfer fees, can cause issues with Balancer pools; and these tokens will be rejected.


If you need help withdrawing liqudity, please contact via Discord or alternatively use [this guide](https://docs.balancer.finance/guides/withdrawing-liquidity-via-etherscan#bonus-points-removing-liquidity-from-a-shared-pool-via-etherscan).

Please note that the pool is not "blacklisted" or removed from the protocol. Some of the tokens are eligible for mining. Anyone can join this pool using etherscan or similar interfaces. On our frontend we take additional measures to make sure users won't lost their funds due to incompatibility of the underlying tokens, as vetting that requires advanced technical knowledge.

Closing.

**Comment by nardholio** [comment]
I cannot withdraw liquidity. It reverts with an error. See https://etherscan.io/tx/0x1e4f6f578f820bd450abd50ca7e381c6f647a6e2c62aa6149ba466d9dcdb048b
