### ISSUE TITLE
HAKKA POOL TRANSACTION WITHOUT BPT TOKEN CREATED 

### ISSUE THREAD

**Issue by LILOJAG** [balancer-labs/pool-management-vue#256]
### Good Morning

I have created 2 transaction in Balancer 
one created the token BPT but does not appear in balancer share liquidity 
The other was succesful but did not create a token and does not appear anywhere 

Can you please help rectify the problem I tried my best but cant resolve that issue 

Thanks
S

![HAKKA BALANCE POOL TRANSACTION II](https://user-images.githubusercontent.com/78412567/106580314-ab839280-6539-11eb-82e6-8f536dc1486a.JPG)
![HAKKA BALANCER POOL TRANSACTION](https://user-images.githubusercontent.com/78412567/106580316-ac1c2900-6539-11eb-85b2-06cdf3dc2b10.JPG)

**Comment by bonustrack** [comment]
Did you used Balancer interface for the second transaction? When you use Balancer to add liquidity it will go through a proxy contract, but on the second transaction i don't see any proxy.

**Comment by LILOJAG** [comment]
YES I followed the exact same process for both 
![HAKKA TRANSACTION STEPS METAMASK](https://user-images.githubusercontent.com/78412567/106605785-34f68d00-6559-11eb-9b75-91b3b8a0c80e.JPG)
![HAKKA REWARD POOL](https://user-images.githubusercontent.com/78412567/106605788-358f2380-6559-11eb-9f7f-f089fc4616dc.JPG)

**Comment by LILOJAG** [comment]
HI THERE CAN YOU PLEASE PROVIDE ME WITH A SOLUTION OR MY TOKENS BACK 
THANKS

**Comment by bonustrack** [comment]
Can you send the transaction ids?

**Comment by LILOJAG** [comment]
HERE YOU GO 
TXN HASH TRANSACTION 
0x94758e6f0511c30d2e762ca19bfee70b8a98575c543c432df8375ed3bcb3c4cd

8000 HAKKA 
TIME STAMP 
5 days 15 hrs ago (Jan-29-2021 05:38:05 AM +UTC)

**Comment by LILOJAG** [comment]
MY Metamask Account used 0x20FF58154bd2c9Bfb7bf37c2F7665DDAA0b97253

**Comment by EndymionJkb** [comment]
Ok - I funderstand what happened!

Your first transaction added liquidity to the Balancer pool, and minted BPT back to you. So far, so good.

The second transaction was where it went wrong. From your UI snapshots, it looks like you were trying to "stake" the BPT on Hakka. You would do this by interacting with the Hakka staking contract, which would have logic to pull in your  *BHS/HAKKA* tokens (the BPT tokens received from the first transaction).

I could be wrong, but since that transaction is just a "transfer" call on the Hakka token, it looks like you didn't use their UI at all, and just hit "Send" from Metamask.

Just as you need to interact with the Balancer protocol to mint BPT, you would need to interact with the Hakka staking contract to successfully stake. What you actually did was send *HAKKA* tokens directly to the BHS/HAKKA Balancer pool.

I have good news and bad news.

The bad news is there's no way to recover the tokens. Simply sending tokens to the pool contract address is just an ERC-20 transfer, and doesn't do anything else (i.e., you're not calling a method on the contract, so it's not executing any of the code necessary to mint BPT).

If this had been a Balancer smart pool, the tokens would be lost forever. Since this is a shared pool, it is possible for the *pool* to recover any tokens sent in this manner, by calling gulp(). Just to be absolutely sure this is what happened, I called gulp with the HAKKA address on the pool contract:

gulp tx:
0x79f1d8c08a395a19d6c9182418a57556a920587e2847f6ba44e8cbd87be2b583

Sure enough, this caused the pool balance to increase by 8,000, confirming that "extra" tokens had in fact been sent to the contract:

11,827,318.629... -> 11,835,318.629... (difference of 8,000)

So you essentially donated HAKKA to the pool, increasing the total supply of tokens - without increasing the total BPT supply. This means the pool shares are now worth slightly more - (exactly as if 8,000 HAKKA had been paid in fees).

So there are actually two pieces of semi-good news:

1) Assuming you still have the BPT (though I don't see them on your MM address, so you must have moved them), it's now worth slightly more than before. You are also earning BAL on whatever address holds the BPT: claimable from claim.balancer.finance.

2) If you were trying to stake them, you still can. Since you transferred HAKKA tokens - not the BPT tokens - you should still have them, and if the HAKKA platform is offering some kind of staking reward, you can still participate. Just make sure you check with them on how to do it properly.
