### ISSUE TITLE
follow up HAKKA POOL TRANSACTION WITHOUT BPT TOKEN CREATED (#256)

### ISSUE THREAD

**Issue by LILOJAG** [balancer-labs/pool-management-vue#257]
Hi 
I did not have the opportunity to clarify and the issue was closed 
Transaction number 1 dated from February and it was not related to the other one I send it to you to show you that I repeated the process and it went well 
transaction 1 of the 8000 Hakka is from 28 January and both are not related 
the Hakka pool contract consist on sending 8000 Hakka to balancer and create  XX of BTP token 
I did create the BTP and accept it on Metamask but something went wrong and instead I sent 8000 HAKKA and could not retrieve my BPT  that I am supposed to stake on the HAKKA contract 

Based on these clarification can you tell me what is appropriate to do with the gulp tx:
0x79f1d8c08a395a19d6c9182418a57556a920587e2847f6ba44e8cbd87be2b583

thanks and sorry for the mess !

![HAKKA TRANSACTION STEPS METAMASK](https://user-images.githubusercontent.com/78412567/107131564-8a22fd80-68cf-11eb-9fd4-70f994d33aaf.JPG)
![BSH_HAKKA POOL](https://user-images.githubusercontent.com/78412567/107131571-9018de80-68cf-11eb-9152-b087e8532e98.JPG)
![HAKKA REWARD POOL](https://user-images.githubusercontent.com/78412567/107131585-ade64380-68cf-11eb-8dd6-c2238b7bee6e.JPG)
![HAKKA BALANCER POOL TRANSACTION](https://user-images.githubusercontent.com/78412567/107131599-c48c9a80-68cf-11eb-911c-69e7a00bd113.JPG)

**Comment by EndymionJkb** [comment]
Let me try to explain as clearly and simply as I can. See below for the full explanation, but in summary:

1) Unfortunately, your 8k Hakka are gone. You sent them directly through Metamask instead of using the Balancer UI, so the smart contract logic needed to mint new BPT and send it to you was never triggered. The BPT aren't "missing" or "stuck" - they were never created.

You must use the Balancer UI to interact successfully with the Balancer protocol! (Likewise, you need to use the Hakka UI to interact successfully with Hakka.)

2) Judging from your screenshots, the first transaction (using both Balancer and Hakka UIs) worked, so you have successfully minted and staked BPT, and are earning Hakka (and possibly BAL as well, if those tokens are whitelisted and Hakka configured their system to work with our BAL mining program). So it wasn't a total loss; you still have that original farm working for you.

3) At any time, you should be able to "unstake" your BPT. I'm not familiar with the Hakka protocol specifically (read their docs for instructions), but generally this ends with the protocol transferring the BPT (plus accrued Hakka) back to your wallet.

When the BPT are in your wallet, you can go to the Balancer UI from the address associated with your proxy (you can tell it's correct when it shows a value in "My Pool Share"), and "Remove Liquidity." This will "burn" your BPT, and withdraw a corresponding amount of HAKKA and BHSc$ tokens from the pool to your wallet. (You can either withdraw both tokens proportionally, or ask for everything in just one of the tokens.)

--- Details ----

There are two kinds of accounts in Ethereum. Your metamask wallet is the first kind: an externally owned account (EOA). That's just an address that can send and receive tokens.

The second is a smart contract - an address that also contains code, the program logic that implements protocols like Balancer and Hakka.

Balancer pools are smart contracts, so when you use the Balancer protocol to exchange tokens for BPT, you need to call functions on the code in those contracts. That is what the Balancer UI is doing for you.

In your first successful transaction, you used the Balancer UI, created a Proxy, and hit the "Add Liquidity" button. That UI made function calls on the contract, and triggered the logic required to accept your tokens and mint BPT. It is complex logic that computes the amount of BPT you will get based on the weights and balances of pool tokens. I can see you used the UI for the first transaction, because the address is a standard proxy contract associated with your Metamask address.

The second time, you did *not* do the same thing. That transaction did not use the Proxy, so it was not done through the Balancer UI. Instead, it looks like you used Metamask "Send" to transfer Hakka tokens from your wallet straight to the pool contract address.

Recall the two types of accounts described above. If you simply transfer tokens between accounts, that's all that happens. Ethereum doesn't even know there's a smart contract there. It will "work" - the tokens will move from your wallet to the smart contract address - but it will *not* invoke the program logic required to compute and mint BPT. For that to happen, you need to call "joinPool" on the smart contract program with the proper arguments, which is what the UI does.

The blockchain is immutable, so once you sent the tokens, there's no way to get them back. There is no way to withdraw tokens from a pool, except by using your BPT to remove liquidity. (If there were any other way, the Balancer protocol would not be secure and permissionless, and nobody would trust it with a billion dollars.)

The best I could do for you was pull the tokens into the pool balance; otherwise they would just be lost forever. That's what gulp() does, which is a public function anyone can call. (I called it myself to save you the $16 gas.)

By transferring Hakka directly in the second transaction, you effectively contributed an 8k Hakka "fee" to the pool. There is no way to get it back - but at least the BPT you already have are now worth slightly more because of it :)

**Comment by LILOJAG** [comment]
Got it !!
thanks a lot for taking the time
