### ISSUE TITLE
Balancer Pool Token for XHDX

### ISSUE THREAD

**Issue by Wildbill530** [balancer-labs/pool-management-vue#272]
I am new to Balancer. Attempted to purchase xHDX in February. Insted of buying xHDX, I somehow purchased Balancer Pool Tokens for xHDX/DAI.

Is there a way to claim the xHDX tokens?

**Comment by EndymionJkb** [comment]
I'm afraid not! That token was an ERC-20 created specifically for that sale, and is now paused - meaning it cannot be transferred.

The HydraDX sale worked like this: you bought xHDX tokens on Ethereum. After the sale, HydraDX paused the contract (locking all xHDX tokens at their current location forever) and did a snapshot of all wallet balances. You could then go through their claims process to get the PolkaDot HDX tokens based on your balance in the snapshot.

The LBP pool that HydraDX created did not allow public LPs, but - the Balancer Protocol is permission-less, so there is no way to prevent this - other unknown people bought tokens and then created additional pools that **did** allow LPs. If you have BPTs instead of xHDX, you must have added liquidity to one of those pools instead of swapping for the token on the exchange, which is the normal way to buy project tokens in an LBP.

You could have removed liquidity from that pool *before* HydraDX froze their token, and the xHDX would have been transferred to your wallet, allowing you to claim HDX. At this point, removing liquidity "multi-asset" will fail, since the xHDX tokens are "frozen," and can no longer be transferred.

All you can do now is remove liquidity "single-asset." To do this, choose another pool token and burn your BPTs to recover your share of it. How much you will get depends on your pool share, and the relative weights and balances of the other tokens. If it's a smaller amount, make sure the gas costs aren't more than the proceeds!

**Comment by Wildbill530** [comment]
Thank you for the explanation!Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: EndymionJkb ***@***.***> Date: 4/10/21  1:21 PM  (GMT-05:00) To: balancer-labs/pool-management-vue ***@***.***> Cc: Wildbill530 ***@***.***>, Author ***@***.***> Subject: Re: [balancer-labs/pool-management-vue] Balancer Pool Token for XHDX (#272) 
Closed #272.
